version: '3'

services:
  go-gin:
    build:
      context: ./backend # Folder where your Go backend code is located
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapping Go app to the host machine
    volumes:
      - ../test-network/organizations:/organizations
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    networks:
      - my-network

  react-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - go-gin # Ensure backend waits for frontend service to be ready
    networks:
      - my-network

  postgres:
    image: postgres:latest
    container_name: bank-db
    environment:
      POSTGRES_DB: BankAccountDB
      POSTGRES_USER: testdev
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
  # database service for accounts and transactions.
